### ISSUE TITLE
NPE in SAFHelper.listFilesFast

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Fuck-Storage-Access-Framework#18]
```
java.lang.NullPointerException: Attempt to get length of null array
	at android.os.Parcel.createException(Parcel.java:1956)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:803)
	at android.content.ContentResolver.query(ContentResolver.java:753)
	at android.content.ContentResolver.query(ContentResolver.java:711)
	at com.github.k1rakishou.fsaf.util.SAFHelper.listFilesFast(SAFHelper.kt:273)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.listFiles(ExternalFileManager.kt:391)
	at com.github.k1rakishou.fsaf.FileManager.listFiles(FileManager.kt:678)
	at com.github.k1rakishou.fsaf.FileManager.traverseDirectory(FileManager.kt:532)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter.moveOldFilesToTheNewDirectory(MediaSettingsControllerPresenter.kt:202)
	at com.github.adamantcheese.chan.ui.controller.settings.MediaSettingsController.lambda$askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory$16$MediaSettingsController(MediaSettingsController.java:522)
	at com.github.adamantcheese.chan.ui.controller.settings.-$$Lambda$MediaSettingsController$2MMLoOIwXgP7VNEqTFosMIebQN8.onClick(Unknown Source:6)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by K1rakishou** [comment]
Haven't seen this crash since the latest release (which was 5 months ago), I guess the problem was in missing synchronization.

**Comment by virtualC9** [comment]
Have you solved this problem? What is the reason. thank you

**Comment by K1rakishou** [comment]
I haven't seen this crash since June (in my app where this library is used) and the last thing I did was synchronizing all public methods, so I guess that was the problem.
