### ISSUE TITLE
kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = FileManagerId(id='ExternalFile')

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Fuck-Storage-Access-Framework#19]
```
E/Kuroba | UNCAUGHT: kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = FileManagerId(id='ExternalFile')
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.getName(FileManager.kt:672)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.areTheSame(FileManager.kt:858)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.settings.base_directory.SharedLocationSetupDelegate.askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory(SharedLocationSetupDelegate.kt:102)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:147)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:120)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$1.run(MediaSettingsControllerPresenter.kt:263)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Unknown Source:2)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Unknown Source:242)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(Unknown Source:98)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

**Comment by K1rakishou** [comment]
Haven't seen this crash since the latest release (which was 5 months ago), I guess the problem was in missing synchronization.
