### ISSUE TITLE
java.lang.IllegalArgumentException: Parent document isn't a directory

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Fuck-Storage-Access-Framework#20]
```
E/DirectoryManager: dir content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba is not a directory
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: Parent document isn't a directory
E/Kuroba | UNCAUGHT: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
E/Kuroba | UNCAUGHT: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/Kuroba | UNCAUGHT: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
E/Kuroba | UNCAUGHT: 	at android.content.ContentResolver.call(ContentResolver.java:2058)
E/Kuroba | UNCAUGHT: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:129)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:202)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:153)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:538)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:224)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by K1rakishou** [comment]
Haven't seen this crash since the latest release (which was 5 months ago), I guess the problem was in missing synchronization.
