### ISSUE TITLE
java.lang.IllegalStateException: Failed to touch /storage/emulated/0/Kuroba (1)/1557043536290.jpg: java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Fuck-Storage-Access-Framework#21]
```
java.lang.IllegalStateException: Failed to touch /storage/emulated/0/Kuroba (1)/1557043536290.jpg: java.io.IOException: No such file or directory
	at android.os.Parcel.readException(Parcel.java:2037)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
	at android.content.ContentProviderClient.call(ContentProviderClient.java:483)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1178)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1160)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:128)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:198)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:149)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:537)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by K1rakishou** [comment]
Haven't seen this crash since the latest release (which was 5 months ago), I guess the problem was in missing synchronization.
