### ISSUE TITLE
Crash "java.lang.IllegalStateException: create() root is already FileRoot, cannot append anything anymore, root = /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/filecache/b242d2460781b1e813c50efa4e9cc1ac.cache, baseDir segments = , segments = "

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Fuck-Storage-Access-Framework#22]
```
java.lang.IllegalStateException: create() root is already FileRoot, cannot append anything anymore, root = /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/filecache/b242d2460781b1e813c50efa4e9cc1ac.cache, baseDir segments = , segments = 
		at com.github.k1rakishou.fsaf.manager.RawFileManager.create(RawFileManager.kt:24)
		at com.github.k1rakishou.fsaf.manager.RawFileManager.create(RawFileManager.kt:14)
		at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:358)
		at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:330)
		at com.github.adamantcheese.chan.core.cache.FileCacheV2.handleFileDownload(FileCacheV2.kt:819)
		at com.github.adamantcheese.chan.core.cache.FileCacheV2.access$handleFileDownload(FileCacheV2.kt:46)
		at com.github.adamantcheese.chan.core.cache.FileCacheV2$initBatchRequestQueue$1$1.apply(FileCacheV2.kt:187)
		at com.github.adamantcheese.chan.core.cache.FileCacheV2$initBatchRequestQueue$1$1.apply(FileCacheV2.kt:46)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:284)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
		at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:236)
		at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
		at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
		at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
		at io.reactivex.Flowable.subscribe(Flowable.java:14935)
		at io.reactivex.Flowable.subscribe(Flowable.java:14882)
		at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
		at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
		at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:764)
```

**Comment by K1rakishou** [comment]
Haven't seen this crash since the latest release (which was 5 months ago), I guess the problem was in missing synchronization.
